services:
  # The Backend Application Service
  guestguard-backend:
    build: .
    container_name: ApnaManger-backend-app
    ports:
      - "5000:5000"
    env_file:
      - .env
    depends_on:
      - mongo
      - redis
    restart: unless-stopped

  # The MongoDB Database Service
  mongo:
    image: mongo:6.0
    container_name: ApnaManger-mongo-db
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db 
    restart: unless-stopped

  # The Redis Cache Service
  redis:
    image: redis:7-alpine
    container_name: ApnaManger-redis-cache
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped

volumes:
  mongo-data:
  redis-data: