services:
  - type: web
    name: Guest-Guard
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGO_URI
        value: mongodb+srv://uttkarshkumar687:ZDqHrkCXxdfLpbzc@cluster0.wv3xwuc.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0
